### PR TITLE
fix: file limit cut fix

### LINKED ISSUE #777: limt 分页 问题
### Describe the bug（Bug 描述）

ca0d58a9b755d8c76699803cba8b4ec
311bb3d492fc849deee10d220e896e7
同样的条件 倒叙查不全

b3a8b5b5b67b63bb676dac4283076d0
ccf6f7655c4b6af22227cbbcd2148f8

倒叙limit给足够大或者不带limit 也能查全

### To Reproduce（Bug 复现步骤）

生产数据不好复现

### Expected behavior（期望结果）

可以正常查询

### Screenshots（屏幕截图）

_No response_

### Logs（完整的错误日志）

_No response_

### Additional context（其他的一些补充内容）

_No response_

### PR DESCRIPTION
**Pull request by lihanxue**
fix #777

### CODE REVIEW

File: engine/immutable/tssp_file_meta.go [hunk 1]
```diff
@@ -375,6 +375,19 @@ type ChunkMeta struct {
 	colMeta     []ColumnMeta
 }
 
+// only use for test,used by engine/record_plan_test.go
```
Comment (shoothzj) [inline engine/immutable/tssp_file_meta.go:378]:
```suggestion
// NewChunkMeta only use for test,used by engine/record_plan_test.go
```

File: engine/record_plan_test.go [hunk 2]
```diff
@@ -1910,10 +1910,16 @@ func (m MocTsspFile) MetaIndexAt(idx int) (*immutable.MetaIndex, error) {
 }
 
 func (m MocTsspFile) MetaIndex(id uint64, tr util.TimeRange) (int, *immutable.MetaIndex, error) {
+	if id == 0527 {
```
Comment (shoothzj) [inline engine/record_plan_test.go:1913]: extract 0527 to constant?

**Review by xiangyu5632 — APPROVED** [review]
