### PR TITLE
test: fix TestGlob using t.TempDir

### LINKED ISSUE #50: CI fails in the test case "TestGlob"
```
--- PASS: TestCpuNum (0.00s)
PASS
coverage: 100.0% of statements in ./...
ok  	github.com/openGemini/openGemini/lib/cpu	0.004s	coverage: 100.0% of statements in ./...
?   	github.com/openGemini/openGemini/lib/das	[no test files]
=== RUN   TestError
--- PASS: TestError (0.00s)
=== RUN   TestUnknown
--- PASS: TestUnknown (0.00s)
=== RUN   TestMessage
--- PASS: TestMessage (0.00s)
=== RUN   TestStack
--- PASS: TestStack (0.00s)
=== RUN   TestConvert
--- PASS: TestConvert (0.00s)
=== RUN   TestEqual
--- PASS: TestEqual (0.00s)
=== RUN   TestQueryError
--- PASS: TestQueryError (0.00s)
PASS
coverage: 95.9% of statements in ./...
ok  	github.com/openGemini/openGemini/lib/errno	0.004s	coverage: 95.9% of statements in ./...
=== RUN   TestGlob
    file_ops_test.go:53: open /tmp/test/a000000001-000000001.tsm: permission denied
--- FAIL: TestGlob (0.00s)
FAIL
coverage: 3.2% of statements in ./...
FAIL	github.com/openGemini/openGemini/lib/fileops	0.021s
FAIL
make: *** [Makefile:79: gotest] Error 1
Error: Process completed with exit code 2.
```

No code in this test case is modified but the test case fails. It's very confusing.

### PR DESCRIPTION
**Pull request by shilinlee**
Signed-off-by: shilinlee <836160610@qq.com>

### What problem does this PR solve?

Issue Number: close #50 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### CODE REVIEW

**Review by xiangyu5632 — APPROVED** [review]

File: lib/fileops/file_ops_test.go [hunk 1]
```diff
@@ -61,35 +59,35 @@ func TestGlob(t *testing.T) {
...
+		t.Fatalf("Glob(%s) failed: %q", tsmPattern, err.Error())
 	}
 	if len(tmpFiles) != len(tsmfile) {
-		t.Fatalf("Glob(/tmp/test/*.tsm) failed")
+		t.Fatalf("Glob(%s) failed", tsmPattern)
 	}
 	for i := 0; i < len(tmpFiles); i++ {
-		if tsmfile[i] != tmpFiles[i] {
-			t.Fatalf("Glob(/tmp/test/*.tsm) failed: expected(%s) but(%s)", tsmfile[i], tmpFiles[i])
+		if path.Join(tmpDir, tsmfile[i]) != tmpFiles[i] {
```
Comment (zedware) [inline lib/fileops/file_ops_test.go:71]: Glob() may not have the files in lexical order, so it is possible that tsmfile[i] and tmpFiles[i]
may mismatch on some operating systems. Same for walfiles[] below.

File: lib/fileops/file_ops_test.go [hunk 2]
```diff
@@ -61,35 +59,35 @@ func TestGlob(t *testing.T) {
 
 	tsmfile := files[0:2]
```
Comment (zedware) [inline lib/fileops/file_ops_test.go:60]: tsmfile => tsmFiles ?

File: lib/fileops/file_ops_test.go [hunk 3]
```diff
@@ -61,35 +59,35 @@ func TestGlob(t *testing.T) {
...
 	}
 	for i := 0; i < len(tmpFiles); i++ {
-		if tsmfile[i] != tmpFiles[i] {
-			t.Fatalf("Glob(/tmp/test/*.tsm) failed: expected(%s) but(%s)", tsmfile[i], tmpFiles[i])
+		if path.Join(tmpDir, tsmfile[i]) != tmpFiles[i] {
+			t.Fatalf("Glob(%s) failed: expected(%s) but(%s)", tsmPattern, tsmfile[i], tmpFiles[i])
 		}
 	}
 
 	walfile := files[5:8]
```
Comment (zedware) [inline lib/fileops/file_ops_test.go:76]: walfile => walFiles?
and lines 79: walFiles => tmpFiles
